### ISSUE TITLE
El grupo no está completo

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twQ103-agencia-de-viajes#1]
Aseguraos que vuestra compañera Paula se una al equipo. Para ello tiene que ir a la sección "Trabajo en Equipo" de Moodle y unirse a vuestro equipo.

**Comment by MPerezMateo** [comment]
Si no lo hacéis los profesores no van a poder verla como miembro de este team

**Comment by Juliauru** [comment]
Ya estáis todas!
